### ISSUE TITLE
Integration with the Tasks app - Calendar app

### ISSUE THREAD

**Issue by pieter-groeneweg** [juliushaertl/deck#31]
Awesome addition to nextcloud! 

Wouldn´t it be nice to have it integrated in the tasks app? To have boards integrate with lists?

**Comment by juliushaertl** [comment]
This is already planned in https://github.com/juliushaertl/deck/issues/15

**Comment by sunjam** [comment]
[Here is the corrected url link to issue 15, adding Caldav support to Deck.](https://github.com/nextcloud/deck/issues/15)
