### ISSUE TITLE
Not working with PostgreSQL

### ISSUE THREAD

**Issue by lachmanfrantisek** [juliushaertl/deck#37]
Thanks a lot for such a nice app, but decks are not saved to database. Probably, there is problem with PostgreSQL. Choosing participants does not work either.

### Steps to reproduce
1. Open app.
2. Create board.
3. Reopen app.

### Expected behaviour
The created board is present.

### Actual behaviour
No boards are present.

# Server configuration

**Web server:** nginx/1.10.3 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.1 (daily) Build:2017-01-31T21:01:21+00:00 97a4688580997d6d80ead7fa7102ffd2414b9234 - 11.0.1.2

**deck version**: 0.1.0

**Log:**

> **Error**	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_deck_board_acl"("board_id","type","participant","permission_edit","permission_share","permission_manage") VALUES(?,?,?,?,?,?)' with params [3, "user", "franta", null, null, null]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "user"

> **Error**	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_deck_board_acl"("board_id","type","participant","permission_edit","permission_share","permission_manage") VALUES(?,?,?,?,?,?)' with params [3, "group", "admin", null, null, null]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "group"

> **Error** Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT id, title, owner, color, archived, 0 as shared FROM oc_deck_boards WHERE owner = ? UNION SELECT boards.id, title, owner, color, archived, 1 as shared FROM oc_deck_boards as boards JOIN oc_deck_board_acl as acl ON boards.id=acl.board_id WHERE acl.participant=? AND acl.type='user' AND boards.owner != ?' with params ["jmeno", "jmeno", "jmeno"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "user" LINE 1: ...cl.board_id WHERE acl.participant=$2 AND acl.type='user' AND... ^

Thank you.

**Comment by juliushaertl** [comment]
Thanks for reporting. I'll have a look.

Might be related to https://github.com/juliushaertl/deck/issues/29

**Comment by lachmanfrantisek** [comment]
Thanks for a quick response.

In this case, there is probably a problem with syntax, not with a value, like in #29, but I don't know.

**Comment by juliushaertl** [comment]
I likely was caused by some leftover string 'user', while the rest of the code has been moved to a simple numerical value. Can you test if #33 fixes the issues for you?

**Comment by lachmanfrantisek** [comment]
Yes, it works. Thank you. Sharing management works as well.
