### ISSUE TITLE
Safari Browser: Not Showing Details

### ISSUE THREAD

**Issue by emresaracoglu** [juliushaertl/deck#48]
Hello

This is nice project! I like it!
I noticed today, deck details is not showing on Safari browser.

**Comment by juliushaertl** [comment]
Thanks for the report. I currently don't have the possibility to test Safari. So if anyone wants to help out, pull requests to fix this are always welcome.

**Comment by joergmschulz** [comment]
The console complains some things about css, maybe this leads to the errors? 

```
[Warning] Invalid CSS property declaration at: * (select2.css, line 10)
[Warning] Unexpected CSS token: : (select2.css, line 55)
[Warning] Unexpected CSS token: : (select2.css, line 67)
[Warning] Unexpected CSS token: : (select2.css, line 195)
[Warning] Unexpected CSS token: : (select2.css, line 277)
[Warning] Unexpected CSS token: : (select2.css, line 289)
[Warning] Unexpected CSS token: : (select2.css, line 532)
[Warning] Unexpected CSS token: : (style.css, line 91)
[Warning] Invalid CSS property declaration at: ; (styles.css, line 20)

```

**Comment by juliushaertl** [comment]
@joergmschulz Only style.css might be the one from the deck app, but I cannot find any issue there. The other css warnings come from nextcloud server or other apps I guess.

**Comment by joergmschulz** [comment]
works with PR  #51
