### ISSUE TITLE
No Details View with Safari

### ISSUE THREAD

**Issue by ntinti** [juliushaertl/deck#49]
### Steps to reproduce

1. Use Safari for Mac OS
2. Klick on the detail menu icon
3. ....

### Expected behaviour
The detail frame should be visible with its functions 

### Actual behaviour
Nothing is shown - only a white frame

### Server configuration
-

**Web server:**
-

**Database:**
MySQL

**PHP version:**
7.0

**Server version:** (see your admin page)
11.0.1

**Deck version:** (see the apps page)
0.1.1

**Updated from an older installed version or fresh install:**
fresh

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

**The content of config/config.php:**

```
Are you kidding?
I want to let you know bugs in your software not to know all about my server ...
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Safari

**Operating system:**
Mac OS Sierra

**Comment by juliushaertl** [comment]
This has already been reported in https://github.com/juliushaertl/deck/issues/48.
